# Generated by Django 4.1.13 on 2024-08-22 06:35

import bson.objectid
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobbies',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(default=None)),
                ('headLine', models.CharField(max_length=200)),
                ('imageUrl', models.TextField(default='https://images.unsplash.com/photo-1632831291403-dbe6cb9df2d3?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, default=bson.objectid.ObjectId, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('logoClass', models.TextField(default=None)),
                ('description', models.TextField(default=None)),
                ('githubLink', models.TextField(default=None)),
            ],
        ),
    ]
